// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgc9tykOFIL9HkuqvpdK_mkl4bF8iWc20',
    appId: '1:872882726732:android:fad97d8e4a321ce42fd1e9',
    messagingSenderId: '872882726732',
    projectId: 'chatonline-cb019',
    databaseURL: 'https://chatonline-cb019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatonline-cb019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBtAU6QueTz1pix6Xv5FpcJFsiWvdJ3o',
    appId: '1:872882726732:ios:f2b121f2058f7be42fd1e9',
    messagingSenderId: '872882726732',
    projectId: 'chatonline-cb019',
    databaseURL: 'https://chatonline-cb019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatonline-cb019.appspot.com',
    iosBundleId: 'com.example.appChatRealtime',
  );

}